combine CI workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,24 +1,38 @@
-name: Verify Metadata
+name: CI
 
 on:
+  # Triggers the workflow on push or pull request events but only for the main branch
+  push:
+    branches: [ master ]
   pull_request:
-    branches:
-      - master
+    branches: [ master ]
+
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
 
 jobs:
-  build:
+  verify_json:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
-        with:
-          fetch-depth: 0
+
+      - name: Install yajl-tools
+        run: sudo apt-get install -qq yajl-tools
+
+      - name: Check that JSON files are valid
+        run: for f in *.json dist/*.json filter_lists/*.json ; do json_verify < $f || echo "$f failed" ; done
+
+  confirm_built:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
 
       - name: Install node
         uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
         with:
-          node-version: "18"
+          node-version: "20"
 
-      - name: Get changed files in the docs folder
+      - name: Get changed resource-related files
         id: changed-files
         uses: tj-actions/changed-files@cbda684547adc8c052d50711417fa61b428a9f88 # v41
         with:
